[tox]
envlist = py311, py312, py313, py314, lint
skip_missing_interpreters = True

[testenv]
extras = test
commands =
    pytest --basetemp={envtmpdir} --cov=carson_living --cov-report=term-missing

[testenv:lint]
commands =
    flake8 carson_living tests scripts
    pylint carson_living tests scripts
